# Generated by Django 3.0.4 on 2020-07-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customertbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50, null=True)),
                ('EmailId', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=20)),
                ('Otp_num', models.CharField(default=False, max_length=10)),
                ('Extra_Id', models.CharField(default=False, max_length=10)),
                ('is_varified', models.BooleanField(default=False)),
            ],
        ),
    ]
