# Generated by Django 3.0.4 on 2020-08-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producttbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=50, null=True)),
                ('Image', models.ImageField(default='image/logo.png', upload_to='image/')),
                ('ProductPrice', models.FloatField()),
            ],
        ),
    ]
