# Generated by Django 3.0.4 on 2020-08-02 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_producttbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carttbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Total_price', models.FloatField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Producttbl')),
                ('user_to_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Customertbl')),
            ],
        ),
    ]
